version: '3.7'
services:
  db:
    image: mysql:5.7
    ports:
      - "3360:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: user
      MYSQL_PASSWORD: root
volumes:
  portainer_data:

